### PR TITLE
fix: POI directions stability and destination-first flow

### LINKED ISSUE #350: POI Directions Button Puts The POI Location As the Start And Not Destination
### Title

POI Directions Button Puts The POI Location As the Start And Not Destination

### Summary

Once the outdoor POIs are fetched, when we go to the POI tab in the navigation bar and click the directions button, it adds the location of the outdoor POI in the start and not destination field in the directions page.

### Error Seen

There is no error message shown, it just behaves incorrectly.

### Cause

This happens because the target wasn't identified properly.

### Steps to Reproduce

1. Click the outdoors POI button to fetch the POIs.
2.  Go to the POI tab in the navigation bar.
3.  Pick a POI and click the directions button.
4.  You will be redirected to the directions tab and the location of the POI will be in the starting and not the destination field.

### Expected Behavior

Once the POI directions button is clicked, the location of the POI should be in the destination field.

### Actual Behavior

Once the POI directions button is clicked, the location of the POI is in the start field.

### Impact

Th user must erase the location from the start field and place it in the destination field, so it is more unnecessary steps.

### Proposed Fix

Redirect the POI location to the proper destination field.

### Example Fix Snippet

```yaml

```

### Screenshots / Evidence

Image

Image

### Fix Commit Link

TBD

### Test Update Commit Link

TBD

### Checklist

- [x] I included replication steps
- [x] I included screenshots or evidence
- [x] I linked the fix commit
- [x] I linked the test update commit
- [x] I confirmed this issue should be labeled as bug

### LINKED ISSUE #355: BUG-[UT] POI Inconsistency
### Title

POI Inconsistency

### Summary

Once the directions to a POI is dismissed and then the POI directions is clicked again, the location does not get loaded on any of the fields.

### Error Seen

No error messages seen., just incorrect behavior.

### Cause

Incorrect loading of the POI location

### Steps to Reproduce

1. Fetch the POIs
2.  Go to the POI tab
3.  Click the directions button on one of the POIs
4.  Erase the location of POI from the field
5.  Click the red x to cancel the routing
6.  Go back to the POI tab
7.  Click the same POI directions button
8.  No location is showing in any of the fields

### Expected Behavior

The POI location should be in the destination field

### Actual Behavior

The POI location does not get loaded

### Impact

User has to put the location manually

### Proposed Fix

Load the POI location properly

### Example Fix Snippet

```yaml

```

### Screenshots / Evidence

https://github.com/user-attachments/assets/01564d3e-b8b5-4464-8e15-4ee839af6cfa

### Fix Commit Link

TBD

### Test Update Commit Link

TBD

### Checklist

- [x] I included replication steps
- [x] I included screenshots or evidence
- [x] I linked the fix commit
- [x] I linked the test update commit
- [x] I confirmed this issue should be labeled as bug

### LINKED ISSUE #356: BUG - [UT] POI Directions Fluctuation
### Title

POI Directions Fluctuation 

### Summary

After selecting a POI from the POI tab and navigating to the directions page, if the POI is cleared and selected again, the POI alternates incorrectly between the starting location and destination fields instead of staying in the intended field.

### Error Seen

No error shown, just incorrect behavior.

### Cause

This happens due to improper POI location association to the intended field.

### Steps to Reproduce

1. Load the POIs
2. Go to the POI tab in the navigation bar
3. Click the directions button of a POI
4. Erase the POI location from the field it appears in
5. Go back to the POI tab from the navigation bar
6. Click the same POI directions button
7. Click on the field where the POI location is indicated

### Expected Behavior

POI directions should stay in the same field unless erased

### Actual Behavior

POI location jumps between start and destination

### Impact

User has to terminate navigation service by clicking the red x and start over

### Proposed Fix

Make sure the location is loaded properly in the intended field.

### Example Fix Snippet

```yaml

```

### Screenshots / Evidence

https://github.com/user-attachments/assets/f095543e-9db9-460e-800d-bda148ef8af3

### Fix Commit Link

TBD

### Test Update Commit Link

TBD

### Checklist

- [x] I included replication steps
- [x] I included screenshots or evidence
- [x] I linked the fix commit
- [x] I linked the test update commit
- [x] I confirmed this issue should be labeled as bug

### PR DESCRIPTION
**Pull request by mijanullah12**
- POI tab: enable POI fetch on focus; always set POI as destination (align with map).
- Clear start when it was the same POI; seed origin from device coords when none set.
- DirectionsHeader: reset local search UI when start/destination context changes.
- Update POIScreen tests and directions mock.

fixes #356, fixes #355, fixes #350

### CODE REVIEW

File: campus-guide/app/(tabs)/poi.tsx [hunk 1]
```diff
@@ -234,18 +249,33 @@ export default function POIScreen() {
       });
       completeT9(true, "poi_directions_opened");
       const building = poiToBuildingAdapter(poi, selectedCampus);
-      if (startBuilding) {
-        setDestinationBuilding(building);
-      } else {
-        setStartBuilding(building);
+
+      // Same behavior as map POI directions: place is always the destination.
```
Comment (TristanGirardi) [inline campus-guide/app/(tabs)/poi.tsx]: Good catch, now POI should be set properly

**Review by TristanGirardi — APPROVED** [review]
