### PR TITLE
fix: Shuttle destination reset & POI fetching on relocation

### LINKED ISSUE #351: BUG -  [UT] POIs keep requesting from API causing app to crash
### Title

Fix POIs to prevent requesting from API causing app to crash

### Summary

POIs feature keeps requesting to generate new point of interest in the given zoomed in area and doesn't stay static once loaded the first time. This causes the app to constantly request and overwork the app.

### Error Seen

- App crashed

### Cause

Overrequest API 429

### Steps to Reproduce

1. Open app and press POI button
2.  Use other features on the app such as indoor map and getting directions
3. Go back to my map page
4. App will likely crash

### Expected Behavior

Should not crash and POIs should be loaded only when the button is clicked and only point of interest near the user.

### Actual Behavior

POIs are regenerated based on what the user sees on the map and not hisactual location causing it to repeatedly request.

### Impact

- App crash

### Proposed Fix

Make POI not keep requesting.

### Example Fix Snippet

```yaml
TO BE DETERMINED
```

### Screenshots / Evidence

App crashed

### Fix Commit Link

TO BE ADDED

### Test Update Commit Link

TO BE ADDED

### Checklist

- [x] I included replication steps
- [x] I included screenshots or evidence
- [x] I linked the fix commit
- [x] I linked the test update commit
- [x] I confirmed this issue should be labeled as bug

### LINKED ISSUE #353: BUG [UT] - Pressing shuttle when getting destination between 2 buildings changes destination to Vanier Building
### Title

Pressing shuttle when getting destination between 2 buildings changes destination to Vanier Building

### Summary

Pressing shuttle when getting destination between 2 buildings changes destination to Vanier Building

### Error Seen

Pressing shuttle when getting destination between 2 buildings changes destination to Vanier Building

### Cause

Wrong destination and start states are set

### Steps to Reproduce

1. Use map
2. Get destination from H to EV
3. Press shuttle

### Expected Behavior

Show no route available with shuttle

### Actual Behavior

Changes destination to Vanier Building

### Impact

Users get wrong directions

### Proposed Fix

Fix shuttle directions

### Example Fix Snippet

```yaml
TO BE DETERMINED
```

### Screenshots / Evidence

Image

### Fix Commit Link

TO BE ADDED

### Test Update Commit Link

TO  BE ADDED

### Checklist

- [x] I included replication steps
- [x] I included screenshots or evidence
- [x] I linked the fix commit
- [x] I linked the test update commit
- [x] I confirmed this issue should be labeled as bug

### PR DESCRIPTION
**Pull request by hendriktebeng**
- DirectionsHeader: remove auto-reset of start/destination when switching to shuttle mode + remove related test
- POIContext: replace map relocation re-fetching with explicit fetchPOIsAt; POIs only load on toggle, not on map movement
- MapView: pass current map region to fetchPOIsAt on toggle; alert user on cooldown
- usePOIs: clear stale results when disabled to prevent previous location flash on next POI press

fixes #351 fixes #353

### CODE REVIEW

File: campus-guide/app/context/POIContext.tsx [hunk 1]
```diff
@@ -40,33 +48,18 @@ interface POIProviderProps {
...
- * POIProvider: Centralized POI state management across tabs.
- * - Persists showPOIs, pois, and search parameters across navigation
- * - Implements smart region change logic with debouncing
- * - Provides shared source of truth for both Map and POI tabs
- */
 export function POIProvider({ children }: POIProviderProps) {
-  // Visibility
   const [showPOIs, setShowPOIs] = useState(false);
   const [selectedPOI, setSelectedPOI] = useState<PointOfInterest | null>(null);
+  const [searchCenter, setSearchCenter] = useState({ lat: 45.4972, lon: -73.5792 });
```
Comment (antholim) [inline campus-guide/app/context/POIContext.tsx]: Is this the initial search center ? We should probably create an object to store it, something like initialSearchCenter

**Review by antholim — APPROVED** [review]
